/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelDatabase;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import java.sql.*;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author Vilardo
 */
public class HotelDatabase extends javax.swing.JFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int cantidad = 0;
    
    DefaultTableModel model = new DefaultTableModel();
    
    
    /**
     * Creates new form HotelDatabase
     */
    public HotelDatabase() {
        initComponents();
        
        Object col[] = {"Cliente", "Nombre", "Apellido", "Direccion", "CodigoPostal", "Telefono", "Email", "Nacionalidad", "Nacimiento", "DNI", 
            "Genero", "Llegada", "Salida", "Pension", "Tipohabitacion", "Ndehabitacion"};
        
        model.setColumnIdentifiers(col);
        jTabla.setModel(model);
        conn = this.ConnectDB();
        this.updateTable();
        
        cantidad = jTabla.getRowCount();
        if(cantidad > 0){
            cantidad = jTabla.getRowCount() - 1;
            int valor = (int)jTabla.getValueAt(cantidad, 0);
            cantidad = valor;
        }else{
            cantidad = 0;
        }
    }
    
    public static Connection ConnectDB(){
        try{
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:hotelDatabase.db");
            return conn;
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
    }  
    
    public void updateTable(){
        conn = this.ConnectDB();
        if(conn != null){
            String sql = "Select Cliente,Nombre,Apellido,Direccion,CodigoPostal,Telefono,Email,Nacionalidad,Nacimiento,DNI,"
                    + "Genero,Llegada,Salida,Pension,Tipohabitacion,Numerohabitacion from hotelDatabase";
            
            try{
                pst = conn.prepareStatement(sql);
                rs = pst.executeQuery();
                Object[] columnData = new Object[16];
                
                while(rs.next()){
                    columnData[0] = rs.getInt("Cliente");
                    columnData[1] = rs.getString("Nombre");
                    columnData[2] = rs.getString("Apellido");
                    columnData[3] = rs.getString("Direccion");
                    columnData[4] = rs.getString("CodigoPostal");
                    columnData[5] = rs.getString("Telefono");
                    columnData[6] = rs.getString("Email");
                    columnData[7] = rs.getString("Nacionalidad");
                    columnData[8] = rs.getString("Nacimiento");
                    columnData[9] = rs.getString("DNI");
                    columnData[10] = rs.getString("Genero");
                    columnData[11] = rs.getString("Llegada");
                    columnData[12] = rs.getString("Salida");
                    columnData[13] = rs.getString("Pension");
                    columnData[14] = rs.getString("Tipohabitacion");
                    columnData[15] = rs.getString("Numerohabitacion");
                    model.addRow(columnData);             
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtCodigoPostal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTxtDni = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonImprimir = new javax.swing.JButton();
        jButtonTotal = new javax.swing.JButton();
        jButtonReiniciar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jTxtCliente18 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTxtCliente19 = new javax.swing.JTextField();
        jTxtCliente20 = new javax.swing.JTextField();
        jTxtTotal = new javax.swing.JTextField();
        jTxtImpuestos = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTxtSubtotal = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla = new javax.swing.JTable();
        jBoxNumeroExternoHabitacion = new javax.swing.JComboBox<>();
        jBoxGenero = new javax.swing.JComboBox<>();
        jBoxPension = new javax.swing.JComboBox<>();
        jBoxTipoHabitacion = new javax.swing.JComboBox<>();
        jBoxNumeroHabitacion = new javax.swing.JComboBox<>();
        jBoxNacionalidad = new com.toedter.components.JLocaleChooser();
        jPickSalida = new com.toedter.calendar.JDateChooser();
        jPickNacimiento = new com.toedter.calendar.JDateChooser();
        jPickLlegada = new com.toedter.calendar.JDateChooser();
        jTxtSalida = new javax.swing.JTextField();
        jTxtNacimiento = new javax.swing.JTextField();
        jTxtLlegada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de inscripcion");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("hotel.png")));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jTxtNombre.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        getContentPane().add(jTxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 160, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jTxtApellido.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        getContentPane().add(jTxtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 160, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setText("Direccion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jTxtDireccion.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        getContentPane().add(jTxtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 160, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel5.setText("Codigo postal");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jTxtCodigoPostal.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        getContentPane().add(jTxtCodigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 160, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setText("Telefono");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jTxtTelefono.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        getContentPane().add(jTxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jTxtEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        getContentPane().add(jTxtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 160, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel8.setText("Nacionalidad");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setText("Fecha de nacimiento");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel10.setText("DNI");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jTxtDni.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        getContentPane().add(jTxtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 160, -1));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel11.setText("Genero");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel12.setText("Fecha de llegada");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel13.setText("Fecha de salida");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel14.setText("Pension");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel15.setText("Tipo de habitacion");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel16.setText("N° habitacion");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel17.setText("N° Ext. habitacion");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanel1.setFocusable(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonImprimir.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButtonImprimir.setText("Imprimir");
        jButtonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, 130, 50));

        jButtonTotal.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButtonTotal.setText("Total");
        jButtonTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTotalActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 130, 50));

        jButtonReiniciar.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButtonReiniciar.setText("Reiniciar");
        jButtonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReiniciarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 130, 50));

        jButtonActualizar.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 130, 50));

        jButtonBorrar.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 130, 50));

        jButtonSalir.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, 130, 50));

        jTxtCliente18.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jPanel1.add(jTxtCliente18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 110, -1));

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel19.setText("Cliente");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel20.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel20.setText("Cliente");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jLabel21.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel21.setText("Cliente");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        jTxtCliente19.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jPanel1.add(jTxtCliente19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 110, -1));

        jTxtCliente20.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jPanel1.add(jTxtCliente20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 110, -1));

        jTxtTotal.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jPanel1.add(jTxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 240, -1));

        jTxtImpuestos.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jPanel1.add(jTxtImpuestos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 240, -1));

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel22.setText("Impuestos");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jTxtSubtotal.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jPanel1.add(jTxtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 240, -1));

        jLabel24.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel24.setText("Total");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel23.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel23.setText("Subtotal");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 1280, 110));

        jTabla.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Nombre", "Apellido", "Direccion", "CodigoPostal", "Telefono", "Email", "Nacionalidad", "Nacimiento", "DNI", "Genero", "Llegada", "Salida", "Pension", "Tipohabitacion", "Numerohabitacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 1220, 540));

        jBoxNumeroExternoHabitacion.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jBoxNumeroExternoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112" }));
        getContentPane().add(jBoxNumeroExternoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 160, -1));

        jBoxGenero.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Hombre", "Mujer", "Otro" }));
        getContentPane().add(jBoxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 160, -1));

        jBoxPension.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jBoxPension.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Media Pension", "Pension Completa" }));
        getContentPane().add(jBoxPension, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 160, -1));

        jBoxTipoHabitacion.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jBoxTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Simple", "Doble", "Family" }));
        getContentPane().add(jBoxTipoHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 160, -1));

        jBoxNumeroHabitacion.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jBoxNumeroHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "001", "002", "003", "004", "005", "006", "007", "008", "009", "010", "011", "012" }));
        getContentPane().add(jBoxNumeroHabitacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 160, -1));
        getContentPane().add(jBoxNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 160, -1));
        getContentPane().add(jPickSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 160, -1));
        getContentPane().add(jPickNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 160, -1));
        getContentPane().add(jPickLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 160, -1));

        jTxtSalida.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        getContentPane().add(jTxtSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 120, 20));

        jTxtNacimiento.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        getContentPane().add(jTxtNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 120, 20));

        jTxtLlegada.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        getContentPane().add(jTxtLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 120, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirActionPerformed
        MessageFormat header = new MessageFormat("Printing in process");
        MessageFormat footer = new MessageFormat("Page (0, number, integer)");
        
        try{
            jTabla.print(JTable.PrintMode.NORMAL, header, footer);
        }catch(Exception e){
            System.err.format("No Printer found", e.getMessage());
        }
    }//GEN-LAST:event_jButtonImprimirActionPerformed

    private void jButtonTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTotalActionPerformed
        double HabitacionSimple = 30;
        double HabitacionDoble = 60;
        double HabitacionFamiliar = 90;
        double mediaPension = 1.17;
        double pensionCompleta = 1.33;
        
        
        SimpleDateFormat Dformat = new SimpleDateFormat("dd-MM-yyyy");
        Date llegada = null;
        Date salida = null;
        
        try{
            llegada = Dformat.parse(Dformat.format(jPickLlegada.getDate()));
            salida = Dformat.parse(Dformat.format(jPickSalida.getDate()));
        }catch(Exception e){
            e.printStackTrace();
        }
        long diferencia = salida.getTime() - llegada.getTime();
        int dias = (int)(diferencia /1000 / 60 /60 /24);
        
        double costo;
        double impuestos;
        double total;
        double tasa_iva = 0.21;
        
        if((String)jBoxTipoHabitacion.getSelectedItem() == "Simple"){
            costo = HabitacionSimple * dias;
        }else if((String)jBoxTipoHabitacion.getSelectedItem() == "Doble"){
            costo = HabitacionDoble * dias;
        }else{
            costo = HabitacionFamiliar * dias;
        }
        
        if((String)jBoxPension.getSelectedItem() == "Media Pension"){
            costo = costo * mediaPension;
        }else{
            costo = costo * pensionCompleta;
        }
        impuestos = costo * tasa_iva;
        total = impuestos + costo;
        
        jTxtSubtotal.setText(String.format("U$D %.2f", costo));
        jTxtImpuestos.setText(String.format("U$D %.2f", impuestos));
        jTxtTotal.setText(String.format("U$D %.2f", total));
    }//GEN-LAST:event_jButtonTotalActionPerformed

    private void jButtonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReiniciarActionPerformed
        /*DefaultTableModel model = (DefaultTableModel) jTabla.getModel();
        model.setRowCount(0);*/
        
        jTxtNombre.setText("");
        jTxtApellido.setText("");
        jTxtDireccion.setText("");
        jTxtCodigoPostal.setText("");
        jTxtTelefono.setText("");
        jTxtEmail.setText("");
        jBoxNacionalidad.setSelectedIndex(0);
        jPickLlegada.setDate(null);
        jTxtLlegada.setText("");
        jPickSalida.setDate(null);
        jTxtSalida.setText("");
        jPickNacimiento.setDate(null);
        jTxtNacimiento.setText("");
        jTxtDni.setText("");
        jBoxGenero.setSelectedIndex(0);
        jBoxPension.setSelectedIndex(0);
        jBoxTipoHabitacion.setSelectedIndex(0);
        jBoxNumeroHabitacion.setSelectedIndex(0);
        jBoxNumeroExternoHabitacion.setSelectedIndex(0);
        jTxtImpuestos.setText("");
        jTxtSubtotal.setText("");
        jTxtTotal.setText("");
    }//GEN-LAST:event_jButtonReiniciarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTabla.getModel();
        model.setRowCount(0);
        
        DateFormat Nacimiento = new SimpleDateFormat("dd-MM-yyyy");
        jTxtNacimiento.setText(Nacimiento.format(jPickNacimiento.getDate()));
        
        DateFormat Llegada = new SimpleDateFormat("dd-MM-yyyy");
        jTxtLlegada.setText(Llegada.format(jPickLlegada.getDate()));
        
        DateFormat Salida = new SimpleDateFormat("dd-MM-yyyy");
        jTxtSalida.setText(Salida.format(jPickSalida.getDate()));
        
        String sql = "INSERT INTO hotelDatabase(Cliente,Nombre,Apellido,Direccion,CodigoPostal,Telefono,Email,Nacionalidad,Nacimiento,DNI,"
                    + "Genero,Llegada,Salida,Pension,Tipohabitacion,Numerohabitacion)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        
        try{
            pst = conn.prepareStatement(sql);
            pst.setInt(1, cantidad+1);
            pst.setString(2, jTxtNombre.getText());
            pst.setString(3, jTxtApellido.getText());
            pst.setString(4, jTxtDireccion.getText());
            pst.setString(5, jTxtCodigoPostal.getText());
            pst.setString(6, jTxtTelefono.getText());
            pst.setString(7, jTxtEmail.getText());
            pst.setString(8, (String) jBoxNacionalidad.getSelectedItem());
            pst.setString(9, jTxtNacimiento.getText());
            pst.setString(10, jTxtDni.getText());
            pst.setString(11, (String) jBoxGenero.getSelectedItem());
            pst.setString(12, jTxtLlegada.getText());
            pst.setString(13, jTxtSalida.getText());
            pst.setString(14, (String) jBoxPension.getSelectedItem());
            pst.setString(15, (String) jBoxTipoHabitacion.getSelectedItem());
            pst.setString(16, (String) jBoxNumeroHabitacion.getSelectedItem());
            
            pst.execute();
            rs.close();
            pst.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        cantidad++;
        this.updateTable();
        
        //DefaultTableModel iModel = (DefaultTableModel) jTabla.getModel();
        if(jTabla.getSelectedRow() == -1){
            if(jTabla.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "Actualizacion de reservas realizada", "Sistema de administracion", JOptionPane.OK_OPTION);
            }
        }
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTabla.getModel();
        int indice;
        Statement st = null;
                
        try{
            st = conn.createStatement();
            if(jTabla.getSelectedRow() == -1){
                if(jTabla.getRowCount() == 0){
                    JOptionPane.showMessageDialog(null, "No hay informacion para borrar", "Sistema de administracion", JOptionPane.OK_OPTION);
                }else{
                    JOptionPane.showMessageDialog(null, "Selecciona la fila para borrar", "Sistema de administracion", JOptionPane.OK_OPTION);
                }
            }else{
                indice = jTabla.getSelectedRow();        
                int aux = (int)jTabla.getValueAt(indice, 0);
                model.removeRow(indice);
                String sql = "Delete from hotelDatabase where Cliente = "+aux;
                st.executeUpdate(sql);        
            }
        }catch(Exception e){
            e.printStackTrace();
        }     
    }//GEN-LAST:event_jButtonBorrarActionPerformed
    
    private JFrame frame;
    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirma si quieres salir", "Sistema de administracion",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
            try {
                conn.close();
            } catch (Exception e){
                e.printStackTrace();
            }
            System.exit(0);
        }
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jBoxGenero;
    private com.toedter.components.JLocaleChooser jBoxNacionalidad;
    private javax.swing.JComboBox<String> jBoxNumeroExternoHabitacion;
    private javax.swing.JComboBox<String> jBoxNumeroHabitacion;
    private javax.swing.JComboBox<String> jBoxPension;
    private javax.swing.JComboBox<String> jBoxTipoHabitacion;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonReiniciar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonTotal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser jPickLlegada;
    private com.toedter.calendar.JDateChooser jPickNacimiento;
    private com.toedter.calendar.JDateChooser jPickSalida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabla;
    private javax.swing.JTextField jTxtApellido;
    private javax.swing.JTextField jTxtCliente18;
    private javax.swing.JTextField jTxtCliente19;
    private javax.swing.JTextField jTxtCliente20;
    private javax.swing.JTextField jTxtCodigoPostal;
    private javax.swing.JTextField jTxtDireccion;
    private javax.swing.JTextField jTxtDni;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtImpuestos;
    private javax.swing.JTextField jTxtLlegada;
    private javax.swing.JTextField jTxtNacimiento;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtSalida;
    private javax.swing.JTextField jTxtSubtotal;
    private javax.swing.JTextField jTxtTelefono;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
}
